import {chromium,expect} from '@playwright/test';
import fs from 'node:fs/promises';
const dir='.impeccable/review/critic-a/post';await fs.mkdir(dir,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
const errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));
const shot=async name=>{await page.screenshot({path:`${dir}/${name}.png`});};
await page.goto('http://localhost:5174');await page.waitForSelector('.is-ready');await page.waitForTimeout(2000);
await page.getByRole('button',{name:'Select Final Fantasy VII',exact:true}).hover();await page.waitForTimeout(600);await shot('dock-hover');
await page.getByRole('button',{name:'Select Tekken 3',exact:true}).focus();await page.mouse.move(10,10);await shot('dock-focus');
await page.getByRole('button',{name:'Inspect the disc'}).click();await page.mouse.move(10,10);await page.waitForTimeout(1700);await shot('detail');
await page.getByRole('button',{name:'Enter its world'}).click();await page.waitForSelector('video');
await expect.poll(()=>page.locator('video').evaluate(v=>v.currentTime),{timeout:20000}).toBeGreaterThan(.4);
results.push(await page.locator('video').evaluate(v=>({source:v.currentSrc,playing:!v.paused,time:v.currentTime,muted:v.muted,ready:v.readyState})));
await page.getByRole('button',{name:'Pause film',exact:true}).click();await page.waitForTimeout(1000);await shot('desktop-film');
await page.locator('video').evaluate(v=>{v.currentTime=Math.max(0,v.duration-.4);});await page.getByRole('button',{name:'Play film',exact:true}).click();await page.getByRole('button',{name:/Next memory:/}).waitFor({timeout:15000});await shot('desktop-ended');
await page.getByRole('button',{name:/Next memory:/}).click();await page.waitForSelector('.memory-viewer',{state:'detached'});results.push({nextTitle:await page.locator('.detail-copy h1').textContent()});await page.getByRole('button',{name:'Enter its world'}).click();await page.waitForSelector('video');await expect.poll(()=>page.locator('video').evaluate(v=>v.currentTime),{timeout:15000}).toBeGreaterThan(.4);
await page.getByRole('button',{name:'Captures',exact:true}).click();await page.getByRole('button',{name:'View frame 3',exact:true}).click();await page.waitForTimeout(1600);await shot('desktop-capture-end');
await page.getByRole('button',{name:'Close memory room',exact:true}).click();await page.waitForSelector('.memory-viewer',{state:'detached'});
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Enter its world'}).click();await page.waitForSelector('video');await expect.poll(()=>page.locator('video').evaluate(v=>v.currentTime),{timeout:15000}).toBeGreaterThan(.4);await page.getByRole('button',{name:'Pause film',exact:true}).click();await page.waitForTimeout(1100);await shot('mobile-film');
await page.getByRole('button',{name:'Captures',exact:true}).click();await page.getByRole('button',{name:'View frame 3',exact:true}).click();await page.waitForTimeout(1500);await shot('mobile-capture-end');
await page.setViewportSize({width:844,height:390});await page.getByRole('button',{name:'Film',exact:false}).click();await page.waitForSelector('video');await expect.poll(()=>page.locator('video').evaluate(v=>v.currentTime),{timeout:15000}).toBeGreaterThan(.4);await page.getByRole('button',{name:'Pause film',exact:true}).click();await page.waitForTimeout(900);await shot('landscape-film');
results.push(await page.evaluate(()=>{const p=document.querySelector('.film-player').getBoundingClientRect();const c=document.querySelector('.memory-close').getBoundingClientRect();return{viewport:[innerWidth,innerHeight],player:{x:p.x,y:p.y,width:p.width,height:p.height},close:{x:c.x,y:c.y,width:c.width,height:c.height}}}));
await page.getByRole('button',{name:'Captures',exact:true}).click();await page.waitForTimeout(1400);await shot('landscape-capture-end');
await page.getByRole('button',{name:'Close memory room',exact:true}).click();await page.waitForSelector('.memory-viewer',{state:'detached'});await shot('landscape-detail');
console.log(JSON.stringify({results,errors},null,2));await fs.writeFile(`${dir}/results.json`,JSON.stringify({results,errors},null,2));await browser.close();
