import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
const out='.impeccable/review/critic-b';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[],results={};page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.__raf=0;const r=window.requestAnimationFrame;window.requestAnimationFrame=cb=>r.call(window,t=>{window.__raf++;cb(t);});});
const shot=async name=>page.screenshot({path:`${out}/${name}.png`});
await page.goto('http://localhost:5174');await page.waitForSelector('.is-ready');await page.waitForTimeout(2500);await shot('desktop');
results.desktop=await page.evaluate(()=>({viewport:[innerWidth,innerHeight],overflow:document.documentElement.scrollWidth>innerWidth,stage:document.querySelector('.gallery-stage').getBoundingClientRect().toJSON()}));
let before=await page.evaluate(()=>window.__raf);await page.waitForTimeout(1100);results.idleRaf=(await page.evaluate(()=>window.__raf))-before;
await page.mouse.click(170,330);await page.waitForTimeout(1200);results.leftDisc={title:await page.locator('h1').innerText(),detail:await page.locator('.spatial-app').evaluate(el=>el.classList.contains('is-detail'))};await shot('left-disc-click');
await page.getByRole('button',{name:'Select Metal Gear Solid',exact:true}).click();await page.getByRole('button',{name:'Inspect the disc'}).click();await page.waitForTimeout(900);await page.getByRole('button',{name:'Enter its world'}).click();await page.waitForSelector('.memory-viewer[open]');await page.waitForTimeout(900);
results.preBack={url:page.url(),memory:await page.locator('.memory-viewer').count()};await page.goBack();await page.waitForTimeout(900);results.postBack={url:page.url(),memory:await page.locator('.memory-viewer').count(),detail:await page.locator('.spatial-app').evaluate(el=>el.classList.contains('is-detail'))};await shot('back-memory');
await page.keyboard.press('Escape');await page.waitForTimeout(700);results.focusAfterEscape=await page.evaluate(()=>({tag:document.activeElement.tagName,text:document.activeElement.textContent}));
await page.getByRole('button',{name:'About',exact:true}).click();await page.waitForTimeout(1200);before=await page.evaluate(()=>window.__raf);await page.waitForTimeout(1000);results.panelRaf=(await page.evaluate(()=>window.__raf))-before;await page.keyboard.press('Escape');
for(const viewport of [{width:844,height:390},{width:1024,height:600},{width:320,height:568}]){await page.setViewportSize(viewport);await page.waitForTimeout(900);results[`viewport-${viewport.width}`]=await page.evaluate(()=>({scrollHeight:document.documentElement.scrollHeight,viewHeight:innerHeight,controls:[...document.querySelectorAll('.artifact-actions button,.browse-controls button,.disc-dock button')].map(el=>({text:el.getAttribute('aria-label')||el.textContent,rect:el.getBoundingClientRect().toJSON()}))}));await shot(`collection-${viewport.width}`);await page.getByRole('button',{name:'Enter its world'}).click();await page.waitForSelector('.memory-viewer[open]');await page.waitForTimeout(900);await shot(`memory-${viewport.width}`);await page.keyboard.press('Escape');await page.waitForTimeout(600);}
const touch=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true,deviceScaleFactor:1});await touch.goto('http://localhost:5174');await touch.waitForSelector('.is-ready');await touch.getByRole('button',{name:'Inspect the disc'}).click();await touch.waitForTimeout(1000);const cdp=await touch.context().newCDPSession(touch);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:200,y:440}]});for(let y=420;y>=140;y-=20){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:200,y}]});await touch.waitForTimeout(25);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await touch.waitForTimeout(700);results.touchSwipe=await touch.evaluate(()=>({scrollY,scrollHeight:document.documentElement.scrollHeight,stage:document.querySelector('.gallery-stage').getBoundingClientRect().toJSON()}));await touch.screenshot({path:`${out}/touch-scroll.png`});
results.errors=errors;await fs.writeFile(`${out}/evidence.json`,JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));await browser.close();
