import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
const browser = await chromium.launch({ executablePath: '/usr/bin/chromium', headless: true, args: ['--no-sandbox', '--enable-unsafe-swiftshader', '--use-gl=angle', '--use-angle=swiftshader'] });
await fs.mkdir('.impeccable/review', { recursive: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto('http://localhost:5173');
await page.waitForSelector('.is-ready');
await page.waitForTimeout(1600);
await page.screenshot({ path: '.impeccable/review/desktop.png', fullPage: true });
console.log('desktop', await page.evaluate(() => ({ width:innerWidth, scroll:document.documentElement.scrollWidth, canvas:!!document.querySelector('canvas'), fonts:document.fonts.status })));
await page.getByRole('button', { name: 'Explore the artifact' }).click();
await page.waitForTimeout(1200);
await page.screenshot({ path: '.impeccable/review/detail.png', fullPage: true });
await page.getByRole('button', { name: 'Turn it over' }).click();
await page.waitForTimeout(1500);
await page.screenshot({ path: '.impeccable/review/reverse.png', fullPage: true });
await page.getByRole('button', { name: 'Index', exact: true }).click();
await page.waitForTimeout(800);
await page.screenshot({ path: '.impeccable/review/index.png', fullPage: true });
await page.getByRole('button', { name: 'About', exact: true }).click();
await page.waitForTimeout(800);
await page.screenshot({ path: '.impeccable/review/about.png', fullPage: true });
await page.setViewportSize({ width: 390, height: 844 });
await page.getByRole('button', { name: 'PLAY BACK home' }).click();
await page.waitForTimeout(1200);
await page.screenshot({ path: '.impeccable/review/mobile.png', fullPage: true });
console.log('mobile', await page.evaluate(() => ({ width:innerWidth, scroll:document.documentElement.scrollWidth })));
await page.getByRole('button', { name: 'Explore the artifact' }).click();
await page.waitForTimeout(1200);
await page.screenshot({ path: '.impeccable/review/mobile-detail.png', fullPage: true });
await page.getByRole('button', { name: 'Index', exact: true }).click();
await page.waitForTimeout(800);
await page.screenshot({ path: '.impeccable/review/mobile-index.png', fullPage: true });
await page.getByRole('button', { name: 'About', exact: true }).click();
await page.waitForTimeout(800);
await page.screenshot({ path: '.impeccable/review/mobile-about.png', fullPage: true });
try {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto('https://a24.raviklaassens.com/', { waitUntil: 'domcontentloaded', timeout: 30000 });
  await page.waitForTimeout(7000);
  await page.screenshot({ path: '.impeccable/review/reference.png' });
} catch (error) { console.log('Reference capture:', error.message); }
console.log('Page errors:', errors);
await browser.close();
