import { chromium, expect } from '@playwright/test';
import fs from 'node:fs/promises';
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']});
const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
const errors=[], checks=[]; page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error') errors.push(m.text());});
const capture=async name=>{await page.screenshot({path:`.impeccable/review/${name}.png`,fullPage:true});};
await page.goto('http://localhost:5174'); await page.waitForSelector('.is-ready');await page.waitForTimeout(1400);await capture('mobile');
await page.getByRole('button',{name:'Next game',exact:true}).click();await expect(page.locator('.artifact-caption h1')).toHaveText('R4: Ridge Racer Type 4');
await page.keyboard.press('ArrowLeft');await expect(page.locator('.artifact-caption h1')).toHaveText('Metal Gear Solid');checks.push('Button and keyboard navigation');
await page.mouse.move(300,300);await page.mouse.down();await page.mouse.move(50,300,{steps:10});await page.mouse.up();await expect(page.locator('.artifact-caption h1')).not.toHaveText('Metal Gear Solid');checks.push('Drag selects a different artifact');
await page.getByRole('button',{name:'Select Metal Gear Solid',exact:true}).click();
await page.getByRole('button',{name:'Enter its world'}).click();await page.waitForSelector('.memory-viewer[open]');await page.waitForTimeout(1600);await capture('mobile-memory');
await page.getByRole('button',{name:'Captures',exact:true}).click();
await expect(page.getByRole('button',{name:'Autoplay frames'})).toBeVisible();
await page.getByRole('button',{name:'Next frame',exact:true}).click();await expect(page.locator('.memory-caption')).toContainText('Inside the tank hangar.');
await page.getByRole('button',{name:'Autoplay frames'}).click();await expect(page.getByRole('button',{name:'Pause sequence'})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Pause sequence'}).click();
await page.keyboard.press('Escape');await page.waitForSelector('.memory-viewer',{state:'detached'});await expect(page.getByRole('button',{name:'Enter its world'})).toBeFocused();checks.push('Memory room navigation, playback toggle, Escape and focus restoration');
await page.getByRole('button',{name:'Inspect the disc'}).click();await page.waitForTimeout(1200);await capture('mobile-detail');
await page.getByRole('button',{name:'Turn it over'}).click();await expect(page.getByRole('button',{name:'Show the artwork'})).toHaveAttribute('aria-pressed','true');await page.keyboard.press('f');await expect(page.getByRole('button',{name:'Turn it over'})).toHaveAttribute('aria-pressed','false');checks.push('Inspection and reverse by button and F key');
await page.getByRole('button',{name:'Enter its world'}).click();await page.waitForSelector('.memory-viewer[open]');await page.getByRole('button',{name:'Captures',exact:true}).click();await page.keyboard.press('ArrowRight');await expect(page.locator('.memory-caption')).toContainText('Inside the tank hangar.');await page.keyboard.press('Escape');await page.waitForSelector('.memory-viewer',{state:'detached'});await expect(page.locator('.spatial-app')).toHaveClass(/is-detail/);checks.push('Modal keys do not change underlying artifact or dismiss inspection');
await page.getByRole('button',{name:'Back to the collection'}).click();
await page.getByRole('button',{name:/^Collection/}).click();await page.waitForTimeout(700);await capture('mobile-index');await page.locator('.archive-panel').getByRole('button',{name:/Tekken 3/}).click();await expect(page.locator('.detail-copy h1')).toHaveText('Tekken 3');checks.push('Index selects and opens artifact');
await page.getByRole('button',{name:'About',exact:true}).click();await page.waitForTimeout(700);await capture('mobile-about');await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Back to the collection'}).click();
for(const width of [320,600,768]){await page.setViewportSize({width,height:900});await page.waitForTimeout(800);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await capture(`width-${width}`);if(width===600){await page.getByRole('button',{name:'Inspect the disc'}).click();await page.waitForTimeout(900);await capture('detail-600');await page.getByRole('button',{name:'Back to the collection'}).click();}}checks.push('320, 390, 600 and 768 px layouts have no horizontal overflow');
await page.setViewportSize({width:1440,height:900});await page.getByRole('button',{name:'Select Metal Gear Solid',exact:true}).click();await page.mouse.move(5,5);await page.waitForTimeout(1200);await capture('desktop');
await page.getByRole('button',{name:'Switch to after-hours lighting'}).click();await page.mouse.move(5,5);await page.waitForTimeout(1100);await capture('night');await page.getByRole('button',{name:'Switch to studio lighting'}).click();checks.push('Both lighting states');
await page.getByRole('button',{name:/^Collection/}).click();await page.waitForTimeout(700);await capture('index');await page.keyboard.press('Escape');
await page.getByRole('button',{name:'About',exact:true}).click();await page.waitForTimeout(700);await capture('about');await page.keyboard.press('Escape');
await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Select Final Fantasy VII',exact:true}).click();await page.getByRole('button',{name:'Inspect the disc'}).click();await page.getByRole('button',{name:'Turn it over'}).click();await expect(page.getByRole('button',{name:'Show the artwork'})).toBeVisible();checks.push('Reduced motion retains inspection controls');
await page.goto('http://localhost:5174/#game/wipeout');await page.waitForSelector('.is-ready');await expect(page.locator('.detail-copy h1')).toHaveText('WipEout');checks.push('Deep link opens correct artifact');
const fallback=await browser.newPage({viewport:{width:390,height:844}});await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type==='webgl2'||type==='webgl'||type==='experimental-webgl')return null;return original.call(this,type,...args);};});await fallback.goto('http://localhost:5174');await fallback.waitForSelector('.is-ready');await expect(fallback.locator('.fallback-scene')).toBeVisible();await fallback.getByRole('button',{name:'Inspect the disc'}).click();await fallback.getByRole('button',{name:'Turn it over'}).click();await expect(fallback.locator('.fallback-reverse')).toBeVisible();checks.push('No-WebGL fallback preserves browsing and inspection');
console.log(JSON.stringify({checks,errors},null,2));await fs.writeFile('.impeccable/review/verification.json',JSON.stringify({checks,errors},null,2));await browser.close();
if(errors.length) process.exitCode=1;
