import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
const dir='.impeccable/review/critic-a';await fs.mkdir(dir,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const shot=async n=>page.screenshot({path:`${dir}/${n}.png`,fullPage:false});
await page.goto('http://localhost:5174');await page.waitForSelector('.is-ready');await page.waitForTimeout(2000);await shot('desktop');
await page.mouse.move(720,350);await page.waitForTimeout(700);await shot('hover');
await page.mouse.down();await page.mouse.move(210,380,{steps:20});await page.mouse.up();await page.waitForTimeout(1000);await shot('drag');
await page.getByRole('button',{name:'Select Metal Gear Solid',exact:true}).click();await page.getByRole('button',{name:'Inspect the disc'}).click();await page.mouse.move(15,15);await page.waitForTimeout(1300);await shot('detail');
await page.getByRole('button',{name:'Turn it over'}).click();await page.waitForTimeout(1200);await shot('reverse');
await page.getByRole('button',{name:'Enter its world'}).click();await page.waitForTimeout(1600);await shot('room');
await page.getByRole('button',{name:'Film',exact:false}).click();await page.waitForTimeout(800);await shot('film');
await page.keyboard.press('Escape');await page.waitForTimeout(700);
const focus=await page.evaluate(()=>document.activeElement?.textContent);
await page.getByRole('button',{name:/^Collection/}).click();await page.waitForTimeout(600);await shot('index');await page.keyboard.press('Escape');
await page.getByRole('button',{name:'About',exact:true}).click();await page.waitForTimeout(600);await shot('about');await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Back to the collection'}).click();await page.setViewportSize({width:390,height:844});await page.waitForTimeout(1200);await shot('mobile');
await page.getByRole('button',{name:'Inspect the disc'}).click();await page.waitForTimeout(1200);await shot('mobile-detail');
await page.getByRole('button',{name:'Enter its world'}).click();await page.waitForTimeout(1200);await shot('mobile-room');
await page.keyboard.press('Escape');await page.waitForTimeout(700);await page.getByRole('button',{name:'Back to the collection'}).click();
await page.setViewportSize({width:1440,height:900});await page.keyboard.press('Tab');await shot('focus');
console.log(JSON.stringify({errors,focus},null,2));
await browser.close();
